--- 
dateformat : "%Y-%m-%dT%H:%M:%S"
geofilter : [CH, CH011, CH021, CH040, CH070]
outputpath : public
mainfile : main.Rmd


# Download
net:
 path : net1
 format : json
 urlPackagelist : https://opendata.swiss/api/3/action/package_list
 pattern : "todesf.*lle.*alter.*kanton.*csv"
 urlPackage : https://opendata.swiss/api/3/action/package_show
 datafile : deathdata.csv
 
# Build data
build:
 path : build1
 releasefile : releasefile.csv
 releaseweeks : 2
 badgescript : badgelinks.R
 restfile : json.json

# Static data
static:
 path : static
 earlydata : "ts-q-01.04.02.01.30.csv"
 metadata : "ts-q-01.04.02.01.30-APPENDIX.xlsx"
 refdatageo : "grossregionCH.csv"
 imagerelease : "firstrelease.png"
 eventfile : "eventlog.csv"

# Content
content:
 path : content

# Public
public:
 path : public
 
 
test:
  path: test
  test1:
    path: test1
    testfile: testfile.txt

