# This is a basic workflow to download data

name: Gold mining

# Controls when the action will run. Triggers the workflow whenever 
on:
#  push:
#    branches:
#      - main
#  schedule: # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
#    - cron:  '55 3 * * *' # run every day morning at 3:55 am

# Automatically download data whenever 
# and commits the results to the master branch.
jobs:
  download:
    name: Download
    runs-on: ubuntu-latest
    container: rocker/verse:3.6.3
    continue-on-error: false
    timeout-minutes: 10
    
    env:
      working-directory: ./opendata/mining
    
    steps:
      # Checkout GitHub 'master'
      - name: Checkout repo
        uses: actions/checkout@v2
        
      # Runing R script will expose return value on 
      - name: Download metadata
        run: Rscript opendata.R
        working-directory: ${{ env.working-directory }}

      # Checking the status will expose the status on 
      # the ${{ steps.changes.outputs.changed }} variable.
      - name: Check if there are changes in the repo
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      # only try to commit if there are actually changes
      - name: Commit and push to repo
        if: steps.changes.outputs.changed == 1 
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          name: GitHub Action Download
          email: normandev@puntaminar.ch
          commit-message: 'Update Todesfallzahlen metedata'

